In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv('/content/all_kindle_review .csv')

In [3]:
df.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [4]:
data = df[['reviewText','rating']]

In [5]:
data.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [6]:
data['rating'].unique()

array([3, 5, 4, 2, 1])

In [7]:
data['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [8]:
data.shape

(12000, 2)

In [9]:
data.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [10]:
data.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [11]:
data['rating'] = data['rating'].apply(lambda x: 1 if x>3 else 0)
#positive 0 negative 1

<ipython-input-11-1211230291>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['rating'] = data['rating'].apply(lambda x: 1 if x>3 else 0)


In [12]:
data.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       0
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       0
3  Aggie is Angela Lansbury who carries pocketboo...       0
4  I did not expect this type of book to be in li...       1

In [13]:
data['rating'].value_counts()

rating
0    6000
1    6000
Name: count, dtype: int64

In [14]:
data['reviewText'] = data['reviewText'].str.lower()

<ipython-input-14-1610592959>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['reviewText'] = data['reviewText'].str.lower()


In [15]:
data.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       0
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       0
3  aggie is angela lansbury who carries pocketboo...       0
4  i did not expect this type of book to be in li...       1

In [16]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [17]:
data['reviewText']=data['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 0-9]+', ' ',x))
data['reviewText']=data['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))

<ipython-input-17-3222095341>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['reviewText']=data['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 0-9]+', ' ',x))
<ipython-input-17-3222095341>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['reviewText']=data['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))


In [18]:
data['reviewText']=data['reviewText'].apply(lambda x:re.sub(r'''(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’]))''', ' ',x))

<ipython-input-18-141775141>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['reviewText']=data['reviewText'].apply(lambda x:re.sub(r'''(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’]))''', ' ',x))


In [19]:
from bs4 import BeautifulSoup

In [20]:
data['reviewText']=data['reviewText'].apply(lambda x:BeautifulSoup(x, 'lxml').get_text())

<ipython-input-20-446648844>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['reviewText']=data['reviewText'].apply(lambda x:BeautifulSoup(x, 'lxml').get_text())


In [21]:
data['reviewText']=data['reviewText'].apply(lambda x:" ".join(x.split()))

<ipython-input-21-419364912>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['reviewText']=data['reviewText'].apply(lambda x:" ".join(x.split()))


In [22]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [23]:
def lemmatized_text(text):
  return ' '.join([lemmatizer.lemmatize(word) for word in text.split()])

In [24]:
data['reviewText']=data['reviewText'].apply(lambda x:lemmatized_text(x))
data.head()

<ipython-input-24-3644692335>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['reviewText']=data['reviewText'].apply(lambda x:lemmatized_text(x))


reviewText  rating
0  jace rankin may short nothing mess man hauled ...       0
1  great short read want put read one sitting sex...       1
2  start saying first four book expecting 34 conc...       0
3  aggie angela lansbury carry pocketbook instead...       0
4  expect type book library pleased find price right       1

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(data['reviewText'],data['rating'],test_size=0.2)

In [27]:
from sklearn.naive_bayes import GaussianNB
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [28]:
cv = CountVectorizer()
tfidf = TfidfVectorizer()
model = GaussianNB()

In [29]:
X_train_cv = cv.fit_transform(X_train).toarray()
X_train_tfidf = tfidf.fit_transform(X_train).toarray()

In [30]:
X_test_cv = cv.transform(X_test).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

In [31]:
X_train_tfidf

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.18626354],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [32]:
model.fit(X_train_cv,y_train)
model.fit(X_train_tfidf,y_train)

GaussianNB()

In [33]:
y_pred1 = model.predict(X_test_cv)
y_pred2 = model.predict(X_test_tfidf)

In [34]:
from sklearn.metrics import accuracy_score,classification_report

In [35]:
print(accuracy_score(y_pred1,y_test))

0.70375


In [36]:
print(accuracy_score(y_pred2,y_test))

0.6695833333333333


In [37]:
print(classification_report(y_pred1,y_test))

              precision    recall  f1-score   support

           0       0.69      0.71      0.70      1170
           1       0.71      0.70      0.71      1230

    accuracy                           0.70      2400
   macro avg       0.70      0.70      0.70      2400
weighted avg       0.70      0.70      0.70      2400



In [38]:
print(classification_report(y_pred2,y_test))

              precision    recall  f1-score   support

           0       0.61      0.69      0.65      1050
           1       0.73      0.65      0.69      1350

    accuracy                           0.67      2400
   macro avg       0.67      0.67      0.67      2400
weighted avg       0.68      0.67      0.67      2400



In [39]:
!pip install gensim

In [48]:
from gensim.models import Word2Vec
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [44]:
words = []
for sent in data['reviewText']:
  sent_token = sent_tokenize(sent)
  for sentence in sent_token:
    words.append(simple_preprocess(sentence))


In [49]:
import gensim
model=gensim.models.Word2Vec(words)

In [50]:
model.wv.index_to_key

['book',
 'story',
 'read',
 'one',
 'character',
 'like',
 'good',
 'would',
 'love',
 'really',
 'time',
 'get',
 'author',
 'series',
 'well',
 'reading',
 'much',
 'first',
 'even',
 'short',
 'way',
 'great',
 'could',
 'know',
 'sex',
 'make',
 'little',
 'two',
 'thing',
 'want',
 'plot',
 'think',
 'romance',
 'also',
 'find',
 'end',
 'life',
 'see',
 'scene',
 'go',
 'enjoyed',
 'never',
 'written',
 'woman',
 'take',
 'kindle',
 'many',
 'lot',
 'year',
 'work',
 'say',
 'thought',
 'interesting',
 'bit',
 'going',
 'found',
 'novel',
 'writing',
 'give',
 'another',
 'liked',
 'loved',
 'better',
 'man',
 'hot',
 'feel',
 'got',
 'star',
 'come',
 'review',
 'still',
 'though',
 'back',
 'reader',
 'enough',
 'people',
 'friend',
 'made',
 'something',
 'page',
 'part',
 'world',
 'bad',
 'free',
 'need',
 'keep',
 'new',
 'relationship',
 'enjoy',
 'together',
 'next',
 'recommend',
 'start',
 'felt',
 'best',
 'word',
 'put',
 'guy',
 'main',
 'however',
 'day',
 'looking

In [51]:
model.corpus_count

12000

In [52]:
model.epochs

5

In [55]:
model.wv.similar_by_key('bad')

[('mean', 0.7840514779090881),
 ('big', 0.7544674277305603),
 ('nothing', 0.7400226593017578),
 ('kind', 0.7376954555511475),
 ('wrong', 0.7264958620071411),
 ('good', 0.7062720060348511),
 ('awful', 0.7000242471694946),
 ('bugged', 0.6970040798187256),
 ('said', 0.6966744661331177),
 ('confused', 0.6963631510734558)]

In [63]:
model.wv['good']

array([ 0.08045275, -0.25249076,  0.05630593,  0.62787473, -0.02126856,
       -0.21582796,  1.1469759 ,  0.5179968 , -1.2971003 , -0.7013317 ,
       -0.25984105, -0.63299024, -0.40689445,  0.0830749 ,  0.10952371,
       -0.54416883,  0.05279466, -0.41391432, -1.3886787 , -0.85610807,
        0.52285415,  0.19668436,  0.21033908, -0.0119778 ,  0.53040975,
        0.48070017, -0.47149813, -0.3550796 , -0.080447  ,  0.9038585 ,
        0.56362665,  0.21983655,  1.0296116 , -0.5201894 , -0.00710052,
        0.31974408, -0.2171351 , -0.58749384, -0.44216084, -1.0620074 ,
        0.35202724, -0.17033724,  0.9757643 ,  0.2560153 , -0.2288384 ,
        0.05442441, -0.4474952 , -0.3893125 , -0.5452131 , -0.08354785,
        0.8719694 , -0.52092516, -0.25576216, -0.08092958, -0.5612622 ,
       -0.31969607,  0.55053926, -0.9813495 , -0.62875843, -0.07453277,
       -0.58498573,  0.13769667,  0.10614   , -0.52106655, -1.5277545 ,
        1.3796301 ,  0.12897927,  0.7671319 , -1.2019894 ,  0.54

In [67]:
import numpy as np
def avg_word2vec(doc,vector_size=100):
  vectors=[model.wv[word] for word in doc if word in model.wv.index_to_key]
  if not vectors:
    return np.zeros(vector_size)
  return np.mean(vectors,axis=0)

In [68]:
from tqdm import tqdm

In [69]:
X=[]
for i in tqdm(range(len(words))):
  #print('Hello',i)
  X.append(avg_word2vec(words[i]))

100%|██████████| 12000/12000 [00:27<00:00, 434.06it/s]


In [72]:
len(X)

12000

In [73]:
X_new=np.array(X)

In [74]:
X_new[0]

array([-0.17736924,  0.29125893,  0.0941784 , -0.04622482,  0.138085  ,
       -0.4725907 ,  0.22927378,  0.588719  , -0.2655477 , -0.163786  ,
       -0.17503077, -0.46289223, -0.05520168,  0.31418845,  0.3420284 ,
       -0.30874938,  0.05151421, -0.37365693, -0.00451789, -0.6288749 ,
        0.07108636,  0.11600996, -0.02147949, -0.03457619, -0.15166394,
       -0.05328573, -0.1573884 , -0.24297065, -0.28846413, -0.00394027,
        0.21601033, -0.09403107,  0.0627234 , -0.2440618 , -0.14308813,
        0.20044631, -0.00691335, -0.27061042, -0.12227901, -0.51268816,
       -0.0387927 , -0.21869875, -0.125594  ,  0.0828337 ,  0.2544989 ,
       -0.1500919 , -0.17093645, -0.01578028,  0.06899811,  0.1724103 ,
       -0.03643749, -0.27325383, -0.02686452,  0.0603462 , -0.14511204,
        0.24533229,  0.10335383, -0.10498795, -0.14311619,  0.05243632,
        0.1977294 ,  0.27686957,  0.03368779,  0.0043093 , -0.39827728,
        0.32747087,  0.13775933,  0.3007353 , -0.4017127 ,  0.27

In [78]:
import pandas as pd

df = pd.DataFrame()
dataframes_to_concat = []
for i in range(0, len(X)):
    dataframes_to_concat.append(pd.DataFrame(X[i].reshape(1, -1)))

df = pd.concat(dataframes_to_concat, ignore_index=True)

In [79]:
df.shape

(12000, 100)

In [80]:
df.head()

0         1         2         3         4         5         6   \
0 -0.177369  0.291259  0.094178 -0.046225  0.138085 -0.472591  0.229274   
1 -0.332427  0.279012 -0.229985  0.092382  0.094031 -0.626333  0.694464   
2 -0.277632  0.373270 -0.109861 -0.076064  0.105659 -0.620143  0.464391   
3 -0.210411  0.336592 -0.167690  0.074382 -0.002560 -0.653288  0.559139   
4 -0.161157  0.257913  0.166947 -0.003973  0.050621 -0.632678  0.181759   

         7         8         9   ...        90        91        92        93  \
0  0.588719 -0.265548 -0.163786  ...  0.356689  0.040488  0.146295  0.157264   
1  0.649204 -0.623994 -0.373752  ...  0.583076  0.024186  0.176128 -0.069048   
2  0.675542 -0.386382 -0.158956  ...  0.446303  0.054750  0.192700  0.059407   
3  0.820332 -0.296097 -0.250997  ...  0.316552  0.006993  0.071682  0.064367   
4  0.751751 -0.397904 -0.134128  ...  0.675401  0.470793  0.065418 -0.271036   

         94        95        96        97        98        99  
0  0.493538  0.430037  0.184722 -0.276806  0.004793 -0.053365  
1  0.556687  0.448409  0.233947 -0.054066 -0.029356 -0.130232  
2  0.566628  0.378459  0.150331 -0.133414 -0.029749 -0.102684  
3  0.569091  0.230600  0.329135  0.047937 -0.043471 -0.154135  
4  0.574487  0.380386  0.023210 -0.250462  0.100722 -0.037798  

[5 rows x 100 columns]

In [81]:
y=data['rating']

In [82]:
y.shape

(12000,)

In [83]:
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2)

In [86]:
X_test.shape

(2400, 100)

In [87]:
y_test.shape

(2400,)

In [88]:
from sklearn.ensemble import RandomForestClassifier

In [89]:
rfc = RandomForestClassifier()

In [90]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [92]:
y_pred = rfc.predict(X_test)

In [93]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.77      0.76      0.76      1185
           1       0.77      0.78      0.77      1215

    accuracy                           0.77      2400
   macro avg       0.77      0.77      0.77      2400
weighted avg       0.77      0.77      0.77      2400

